// @ai-generated(guided)
//
// Generate Sources/SwiftLocalize/Languages+Generated.swift from CLDR likelySubtags.
//
// Usage:
//   swift run GenerateLanguageConstants <likelySubtags.json> [<output.swift>]
//
// Source data: https://github.com/unicode-org/cldr-json
//   cldr-core/supplemental/likelySubtags.json
//
// Emits one `static let <code>: Language = "<code>"` per ISO 639-1 (2-letter)
// primary subtag found in CLDR. CLDR ships ~600 primary subtags including
// ISO 639-3 codes for tiny languages; we restrict to the ~180 2-letter codes
// apps actually localize against — adding 400+ static members of `Language`
// would just clutter autocomplete. Drop the `count == 2` filter below if you
// need 3-letter codes.

import Foundation

// MARK: - Args

let argv = CommandLine.arguments

guard argv.count >= 2 else {
	FileHandle.standardError.write(Data(
		"usage: swift run GenerateLanguageConstants <likelySubtags.json> [<output.swift>]\n".utf8
	))
	exit(2)
}

let likelyPath = argv[1]
let outputPath = argv.count >= 3 ? argv[2] : "Sources/SwiftLocalize/Languages+Generated.swift"

// MARK: - Load

let data = try Data(contentsOf: URL(fileURLWithPath: likelyPath))
guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
      let supp = root["supplemental"] as? [String: Any],
      let likely = supp["likelySubtags"] as? [String: String]
else {
	FileHandle.standardError.write(Data(
		"not a CLDR likelySubtags.json: \(likelyPath)\n".utf8
	))
	exit(1)
}

// MARK: - Collect primary subtags

// Primary subtag = the part before "_" in each CLDR key (e.g. "en_Latn_GB" → "en").
// Restrict to ISO 639-1 codes (exactly 2 ASCII letters).
var codes = Set<String>()
for key in likely.keys {
	let primary = key.split(separator: "_", maxSplits: 1).first.map(String.init) ?? key
	guard primary.count == 2, primary.allSatisfy(\.isLetter) else { continue }
	codes.insert(primary.lowercased())
}

let sorted = codes.sorted()

// MARK: - Emit

// Swift keywords that collide with 2-letter ISO 639-1 codes. Must be backtick-escaped
// when used as identifiers. `do` = Dogri, `as` = Assamese, `is` = Icelandic, `in` is
// a deprecated alias for Indonesian (CLDR drops it but keep the guard in case).
let swiftKeywords: Set<String> = ["as", "do", "in", "is"]

func ident(_ code: String) -> String {
	swiftKeywords.contains(code) ? "`\(code)`" : code
}

var out = ""
out += "// @ai-generated(guided) — DO NOT EDIT BY HAND.\n"
out += "// Generated by Scripts/GenerateLanguageConstants from CLDR likelySubtags.json.\n"
out += "// Regenerate after CLDR updates:\n"
out += "//   swift run GenerateLanguageConstants <likelySubtags.json> [<output.swift>]\n"
out += "//\n"
out += "// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/likelySubtags.json)\n"
out += "import Foundation\n\n"
out += "public extension Language {\n\n"
for code in sorted {
	out += "\tstatic let \(ident(code)): Language = \"\(code)\"\n"
}
out += "}\n"

try out.write(to: URL(fileURLWithPath: outputPath), atomically: true, encoding: .utf8)
print("wrote \(outputPath): languages=\(sorted.count)")
