// @ai-generated(guided)
//
// Generate Sources/SwiftLocalize/Languages+Generated.swift from CLDR likelySubtags.
//
// Usage:
//   swift run GenerateLanguageConstants [<likelySubtags.json|URL>] [<output.swift>]
//
// Source data: https://github.com/unicode-org/cldr-json
//   cldr-core/supplemental/likelySubtags.json
//
// With no path argument, the file is fetched live from the CLDR JSON repo
// (branch defaults to `main`; override via `CLDR_BRANCH`).
//
// Emits one `static let <code>: Language = "<code>"` per ISO 639-1 (2-letter)
// primary subtag found in CLDR. CLDR ships ~600 primary subtags including
// ISO 639-3 codes for tiny languages; we restrict to the ~180 2-letter codes
// apps actually localize against — adding 400+ static members of `Language`
// would just clutter autocomplete. Drop the `count == 2` filter below if you
// need 3-letter codes.

import Foundation

// MARK: - CLDR source

let cldrBranch = ProcessInfo.processInfo.environment["CLDR_BRANCH"] ?? "main"
let cldrBase = "https://raw.githubusercontent.com/unicode-org/cldr-json/\(cldrBranch)/cldr-json"

/// Read a JSON source as `Data`. Accepts either a local filesystem path or
/// an `http(s)://` URL. Used so scripts default to live CLDR downloads while
/// preserving the ability to point at a locally-pinned snapshot.
func loadData(_ source: String) throws -> Data {
	if source.hasPrefix("http://") || source.hasPrefix("https://") {
		guard let url = URL(string: source) else {
			throw NSError(domain: "load", code: 1, userInfo: [NSLocalizedDescriptionKey: "bad URL: \(source)"])
		}
		FileHandle.standardError.write(Data("fetching \(source)\n".utf8))
		return try Data(contentsOf: url)
	}
	return try Data(contentsOf: URL(fileURLWithPath: source))
}

// MARK: - Args

let argv = CommandLine.arguments

// Treat a positional arg starting with `-` as unsupported to keep room for
// future flag handling without ambiguity against file paths.
let positional = Array(argv.dropFirst()).filter { !$0.hasPrefix("-") }

let likelySource = positional.count >= 1
	? positional[0]
	: "\(cldrBase)/cldr-core/supplemental/likelySubtags.json"
let outputPath = positional.count >= 2
	? positional[1]
	: "Sources/SwiftLocalize/Languages+Generated.swift"

// MARK: - Load

let data = try loadData(likelySource)
guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
      let supp = root["supplemental"] as? [String: Any],
      let likely = supp["likelySubtags"] as? [String: String]
else {
	FileHandle.standardError.write(Data(
		"not a CLDR likelySubtags.json: \(likelySource)\n".utf8
	))
	exit(1)
}

// MARK: - Collect primary subtags

// Primary subtag = the part before "_" in each CLDR key (e.g. "en_Latn_GB" → "en").
// Restrict to ISO 639-1 codes (exactly 2 ASCII letters).
var codes = Set<String>()
for key in likely.keys {
	let primary = key.split(separator: "_", maxSplits: 1).first.map(String.init) ?? key
	guard primary.count == 2, primary.allSatisfy(\.isLetter) else { continue }
	codes.insert(primary.lowercased())
}

let sorted = codes.sorted()

// MARK: - Emit

// Swift keywords that collide with 2-letter ISO 639-1 codes. Must be backtick-escaped
// when used as identifiers. `do` = Dogri, `as` = Assamese, `is` = Icelandic, `in` is
// a deprecated alias for Indonesian (CLDR drops it but keep the guard in case).
let swiftKeywords: Set<String> = ["as", "do", "in", "is"]

func ident(_ code: String) -> String {
	swiftKeywords.contains(code) ? "`\(code)`" : code
}

var out = ""
out += "// @ai-generated(guided) — DO NOT EDIT BY HAND.\n"
out += "// Generated by Scripts/GenerateLanguageConstants from CLDR likelySubtags.json.\n"
out += "// Regenerate after CLDR updates:\n"
out += "//   swift run GenerateLanguageConstants [<likelySubtags.json|URL>] [<output.swift>]\n"
out += "//\n"
out += "// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/likelySubtags.json)\n"
out += "import Foundation\n\n"
out += "public extension Language {\n\n"
for code in sorted {
	out += "\tstatic let \(ident(code)): Language = \"\(code)\"\n"
}
out += "}\n"

try out.write(to: URL(fileURLWithPath: outputPath), atomically: true, encoding: .utf8)
print("wrote \(outputPath): languages=\(sorted.count)")
