// @ai-generated(guided) — DO NOT EDIT BY HAND.
// Generated by Scripts/GenerateGrammaticalGender from CLDR data.
// Regenerate after CLDR updates:
//   swift run GenerateGrammaticalGender [<grammaticalFeatures.json|URL>] [<output.swift>]
//
// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/grammaticalFeatures.json)
import Foundation

internal enum GrammaticalGenderData {

	/// Grammatical genders per language per CLDR `grammaticalFeatures.json`.
	/// Keyed by primary BCP-47 subtag (`ru`, `de`, `cs`). Languages absent
	/// from this map have no grammatical gender system (en, ja, zh, …).
	static let genders: [String: Set<GrammaticalGender>] = [
		"ar": [.masculine, .feminine],
		"ca": [.masculine, .feminine],
		"cs": [.animate, .inanimate, .feminine, .neuter],
		"da": [.common, .neuter],
		"de": [.masculine, .feminine, .neuter],
		"el": [.masculine, .feminine, .neuter],
		"es": [.masculine, .feminine],
		"fr": [.masculine, .feminine],
		"gu": [.masculine, .feminine, .neuter],
		"he": [.masculine, .feminine],
		"hi": [.masculine, .feminine],
		"hr": [.animate, .inanimate, .feminine, .neuter],
		"is": [.masculine, .feminine, .neuter],
		"it": [.masculine, .feminine],
		"kn": [.masculine, .feminine, .neuter],
		"lt": [.masculine, .feminine],
		"lv": [.masculine, .feminine],
		"ml": [.animate, .inanimate, .feminine, .neuter],
		"mr": [.masculine, .feminine, .neuter],
		"nb": [.masculine, .feminine, .neuter],
		"nl": [.common, .neuter],
		"nn": [.masculine, .feminine, .neuter],
		"no": [.masculine, .feminine, .neuter],
		"pa": [.masculine, .feminine],
		"pl": [.animate, .inanimate, .personal, .feminine, .neuter],
		"pt": [.masculine, .feminine],
		"ro": [.masculine, .feminine, .neuter],
		"ru": [.masculine, .feminine, .neuter],
		"si": [.masculine, .feminine, .neuter],
		"sk": [.animate, .inanimate, .feminine, .neuter],
		"sl": [.masculine, .feminine, .neuter],
		"sr": [.animate, .inanimate, .feminine, .neuter],
		"sv": [.common, .neuter],
		"uk": [.masculine, .feminine, .neuter],
		"ur": [.masculine, .feminine],
	]
}
