// @ai-generated(guided) — DO NOT EDIT BY HAND.
// Generated by Scripts/GeneratePluralRanges from CLDR data.
// Regenerate after CLDR updates:
//   swift run GeneratePluralRanges [<pluralRanges.json|URL>] [<output.swift>]
//
// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/pluralRanges.json)
import Foundation

internal enum PluralRangeData {

	/// Category-of-range table per CLDR `pluralRanges.json`. Indexed by primary
	/// BCP-47 subtag, then by the start endpoint's category, then by the end
	/// endpoint's category. The result is the plural category to use for the
	/// whole range — e.g. `ranges["ru"]?[.one]?[.many] == .many` ("1\u{2013}5 яблок").
	///
	/// Languages absent from this map have no CLDR range data; callers fall
	/// back to the end endpoint's own plural category (UTS \#35).
	static let ranges: [String: [PluralCategory: [PluralCategory: PluralCategory]]] = [
		"af": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"ak": [
			.one: [.one: .other, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"am": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"an": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"ar": [
			.zero: [.one: .zero, .two: .zero, .few: .few, .many: .many, .other: .other],
			.one: [.two: .other, .few: .few, .many: .many, .other: .other],
			.two: [.few: .few, .many: .many, .other: .other],
			.few: [.few: .few, .many: .many, .other: .other],
			.many: [.few: .few, .many: .many, .other: .other],
			.other: [.one: .other, .two: .other, .few: .few, .many: .many, .other: .other],
		],
		"as": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"az": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"be": [
			.one: [.one: .one, .few: .few, .many: .many, .other: .other],
			.few: [.one: .one, .few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"bg": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"bn": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"bs": [
			.one: [.one: .one, .few: .few, .other: .other],
			.few: [.one: .one, .few: .few, .other: .other],
			.other: [.one: .one, .few: .few, .other: .other],
		],
		"ca": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"cs": [
			.one: [.few: .few, .many: .many, .other: .other],
			.few: [.few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"cy": [
			.zero: [.one: .one, .two: .two, .few: .few, .many: .many, .other: .other],
			.one: [.two: .two, .few: .few, .many: .many, .other: .other],
			.two: [.few: .few, .many: .many, .other: .other],
			.few: [.many: .many, .other: .other],
			.many: [.other: .other],
			.other: [.one: .one, .two: .two, .few: .few, .many: .many, .other: .other],
		],
		"da": [
			.one: [.one: .one, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"de": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"el": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"en": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"es": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"et": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"eu": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"fa": [
			.one: [.one: .other, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"fi": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"fil": [
			.one: [.one: .one, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"fr": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"ga": [
			.one: [.two: .two, .few: .few, .many: .many, .other: .other],
			.two: [.few: .few, .many: .many, .other: .other],
			.few: [.few: .few, .many: .many, .other: .other],
			.many: [.many: .many, .other: .other],
			.other: [.one: .one, .two: .two, .few: .few, .many: .many, .other: .other],
		],
		"gl": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"gsw": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"gu": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"he": [
			.one: [.two: .other, .other: .other],
			.two: [.other: .other],
			.other: [.one: .other, .two: .other, .other: .other],
		],
		"hi": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"hr": [
			.one: [.one: .one, .few: .few, .other: .other],
			.few: [.one: .one, .few: .few, .other: .other],
			.other: [.one: .one, .few: .few, .other: .other],
		],
		"hu": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"hy": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"ia": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"id": [
			.other: [.other: .other],
		],
		"io": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"is": [
			.one: [.one: .one, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"it": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"ja": [
			.other: [.other: .other],
		],
		"ka": [
			.one: [.other: .one],
			.other: [.one: .other, .other: .other],
		],
		"kk": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"km": [
			.other: [.other: .other],
		],
		"kn": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"ko": [
			.other: [.other: .other],
		],
		"ky": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"lij": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"lo": [
			.other: [.other: .other],
		],
		"lt": [
			.one: [.one: .one, .few: .few, .many: .many, .other: .other],
			.few: [.one: .one, .few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"lv": [
			.zero: [.zero: .other, .one: .one, .other: .other],
			.one: [.zero: .other, .one: .one, .other: .other],
			.other: [.zero: .other, .one: .one, .other: .other],
		],
		"mk": [
			.one: [.one: .other, .other: .other],
			.other: [.one: .other, .other: .other],
		],
		"ml": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"mn": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"mr": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"ms": [
			.other: [.other: .other],
		],
		"my": [
			.other: [.other: .other],
		],
		"nb": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"ne": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"nl": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"no": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"or": [
			.one: [.one: .other, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"pa": [
			.one: [.one: .one, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"pcm": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"pl": [
			.one: [.few: .few, .many: .many, .other: .other],
			.few: [.few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"ps": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"pt": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
		"ro": [
			.one: [.few: .few, .other: .other],
			.few: [.one: .few, .few: .few, .other: .other],
			.other: [.few: .few, .other: .other],
		],
		"ru": [
			.one: [.one: .one, .few: .few, .many: .many, .other: .other],
			.few: [.one: .one, .few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"sc": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"scn": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"sd": [
			.one: [.one: .other, .other: .other],
			.other: [.one: .one, .other: .other],
		],
		"si": [
			.one: [.one: .one, .other: .other],
			.other: [.one: .other, .other: .other],
		],
		"sk": [
			.one: [.few: .few, .many: .many, .other: .other],
			.few: [.few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"sl": [
			.one: [.one: .few, .two: .two, .few: .few, .other: .other],
			.two: [.one: .few, .two: .two, .few: .few, .other: .other],
			.few: [.one: .few, .two: .two, .few: .few, .other: .other],
			.other: [.one: .few, .two: .two, .few: .few, .other: .other],
		],
		"sq": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"sr": [
			.one: [.one: .one, .few: .few, .other: .other],
			.few: [.one: .one, .few: .few, .other: .other],
			.other: [.one: .one, .few: .few, .other: .other],
		],
		"sv": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"sw": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"ta": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"te": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"th": [
			.other: [.other: .other],
		],
		"tk": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"tr": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"ug": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"uk": [
			.one: [.one: .one, .few: .few, .many: .many, .other: .other],
			.few: [.one: .one, .few: .few, .many: .many, .other: .other],
			.many: [.one: .one, .few: .few, .many: .many, .other: .other],
			.other: [.one: .one, .few: .few, .many: .many, .other: .other],
		],
		"ur": [
			.one: [.other: .other],
			.other: [.one: .other, .other: .other],
		],
		"uz": [
			.one: [.other: .other],
			.other: [.one: .one, .other: .other],
		],
		"vi": [
			.other: [.other: .other],
		],
		"yue": [
			.other: [.other: .other],
		],
		"zh": [
			.other: [.other: .other],
		],
		"zu": [
			.one: [.one: .one, .other: .other],
			.other: [.other: .other],
		],
	]
}
