// @ai-generated(guided) — DO NOT EDIT BY HAND.
// Generated by Scripts/GeneratePluralRules from CLDR data.
// Regenerate after CLDR updates:
//   swift run GeneratePluralRules <plurals.json> <ordinals.json> [<output.swift>]
//
// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/)
import Foundation

private extension PluralRule {

	static let _af: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ak: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _am: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _an: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ar: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 0 { return .zero }
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			if (3.0 ... 10.0).contains(absN.truncatingRemainder(dividingBy: 100)) { return .few }
			if (11.0 ... 99.0).contains(absN.truncatingRemainder(dividingBy: 100)) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ars: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 0 { return .zero }
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			if (3.0 ... 10.0).contains(absN.truncatingRemainder(dividingBy: 100)) { return .few }
			if (11.0 ... 99.0).contains(absN.truncatingRemainder(dividingBy: 100)) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _as: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 5 || absN == 7 || absN == 8 || absN == 9 || absN == 10) { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			if absN == 6 { return .many }
			return .other
		}
	)
	
	static let _asa: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ast: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _az: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (((i % 10) == 1 || (i % 10) == 2 || (i % 10) == 5 || (i % 10) == 7 || (i % 10) == 8)) || (((i % 100) == 20 || (i % 100) == 50 || (i % 100) == 70 || (i % 100) == 80)) { return .one }
			if (((i % 10) == 3 || (i % 10) == 4)) || (((i % 1000) == 100 || (i % 1000) == 200 || (i % 1000) == 300 || (i % 1000) == 400 || (i % 1000) == 500 || (i % 1000) == 600 || (i % 1000) == 700 || (i % 1000) == 800 || (i % 1000) == 900)) { return .few }
			if (i == 0) || ((i % 10) == 6) || (((i % 100) == 40 || (i % 100) == 60 || (i % 100) == 90)) { return .many }
			return .other
		}
	)
	
	static let _be: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (absN.truncatingRemainder(dividingBy: 100) != 11) { return .one }
			if ((2.0 ... 4.0).contains(absN.truncatingRemainder(dividingBy: 10))) && (!(12.0 ... 14.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .few }
			if (absN.truncatingRemainder(dividingBy: 10) == 0) || ((5.0 ... 9.0).contains(absN.truncatingRemainder(dividingBy: 10))) || ((11.0 ... 14.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .many }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if ((absN.truncatingRemainder(dividingBy: 10) == 2 || absN.truncatingRemainder(dividingBy: 10) == 3)) && (!(absN.truncatingRemainder(dividingBy: 100) == 12 || absN.truncatingRemainder(dividingBy: 100) == 13)) { return .few }
			return .other
		}
	)
	
	static let _bem: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _bez: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _bg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _bho: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _bm: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _bn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 5 || absN == 7 || absN == 8 || absN == 9 || absN == 10) { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			if absN == 6 { return .many }
			return .other
		}
	)
	
	static let _bo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _br: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (!(absN.truncatingRemainder(dividingBy: 100) == 11 || absN.truncatingRemainder(dividingBy: 100) == 71 || absN.truncatingRemainder(dividingBy: 100) == 91)) { return .one }
			if (absN.truncatingRemainder(dividingBy: 10) == 2) && (!(absN.truncatingRemainder(dividingBy: 100) == 12 || absN.truncatingRemainder(dividingBy: 100) == 72 || absN.truncatingRemainder(dividingBy: 100) == 92)) { return .two }
			if (((3.0 ... 4.0).contains(absN.truncatingRemainder(dividingBy: 10)) || absN.truncatingRemainder(dividingBy: 10) == 9)) && (!((10.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (70.0 ... 79.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (90.0 ... 99.0).contains(absN.truncatingRemainder(dividingBy: 100)))) { return .few }
			if (absN != 0) && (absN.truncatingRemainder(dividingBy: 1000000) == 0) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _brx: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _bs: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ca: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 3) { return .one }
			if absN == 2 { return .two }
			if absN == 4 { return .few }
			return .other
		}
	)
	
	static let _ce: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ceb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if ((isInteger) && ((i == 1 || i == 2 || i == 3))) || ((isInteger) && (!((i % 10) == 4 || (i % 10) == 6 || (i % 10) == 9))) || (!isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _cgg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _chr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ckb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _cs: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if ((2 ... 4).contains(i)) && (isInteger) { return .few }
			if !isInteger { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _cy: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 0 { return .zero }
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			if absN == 3 { return .few }
			if absN == 6 { return .many }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 0 || absN == 7 || absN == 8 || absN == 9) { return .zero }
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			if (absN == 3 || absN == 4) { return .few }
			if (absN == 5 || absN == 6) { return .many }
			return .other
		}
	)
	
	static let _da: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _de: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _dsb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 100) == 1) { return .one }
			if (isInteger) && ((i % 100) == 2) { return .two }
			if (isInteger) && ((3 ... 4).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _dv: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _dz: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ee: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _el: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _en: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (absN.truncatingRemainder(dividingBy: 100) != 11) { return .one }
			if (absN.truncatingRemainder(dividingBy: 10) == 2) && (absN.truncatingRemainder(dividingBy: 100) != 12) { return .two }
			if (absN.truncatingRemainder(dividingBy: 10) == 3) && (absN.truncatingRemainder(dividingBy: 100) != 13) { return .few }
			return .other
		}
	)
	
	static let _eo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _es: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _et: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _eu: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _fa: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ff: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0 || i == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _fi: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _fil: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if ((isInteger) && ((i == 1 || i == 2 || i == 3))) || ((isInteger) && (!((i % 10) == 4 || (i % 10) == 6 || (i % 10) == 9))) || (!isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _fo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _fr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0 || i == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _fur: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _fy: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ga: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			if (3.0 ... 6.0).contains(absN) { return .few }
			if (7.0 ... 10.0).contains(absN) { return .many }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _gd: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN == 1 || absN == 11) { return .one }
			if (absN == 2 || absN == 12) { return .two }
			if ((3.0 ... 10.0).contains(absN) || (13.0 ... 19.0).contains(absN)) { return .few }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 11) { return .one }
			if (absN == 2 || absN == 12) { return .two }
			if (absN == 3 || absN == 13) { return .few }
			return .other
		}
	)
	
	static let _gl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _gsw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _gu: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			if absN == 6 { return .many }
			return .other
		}
	)
	
	static let _guw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _gv: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) { return .one }
			if (isInteger) && ((i % 10) == 2) { return .two }
			if (isInteger) && (((i % 100) == 0 || (i % 100) == 20 || (i % 100) == 40 || (i % 100) == 60 || (i % 100) == 80)) { return .few }
			if !isInteger { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ha: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _haw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _he: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if (i == 2) && (isInteger) { return .two }
			if (isInteger) && (!(0.0 ... 10.0).contains(absN)) && (absN.truncatingRemainder(dividingBy: 10) == 0) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _hi: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			if absN == 6 { return .many }
			return .other
		}
	)
	
	static let _hr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _hsb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 100) == 1) { return .one }
			if (isInteger) && ((i % 100) == 2) { return .two }
			if (isInteger) && ((3 ... 4).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _hu: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 5) { return .one }
			return .other
		}
	)
	
	static let _hy: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0 || i == 1) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _ia: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _id: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ig: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ii: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _in: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _io: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _is: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _it: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 11 || absN == 8 || absN == 80 || absN == 800) { return .many }
			return .other
		}
	)
	
	static let _iu: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _iw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if (i == 2) && (isInteger) { return .two }
			if (isInteger) && (!(0.0 ... 10.0).contains(absN)) && (absN.truncatingRemainder(dividingBy: 10) == 0) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ja: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _jbo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _jgo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ji: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _jmc: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _jv: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _jw: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ka: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if i == 1 { return .one }
			if (i == 0) || (((2 ... 20).contains((i % 100)) || (i % 100) == 40 || (i % 100) == 60 || (i % 100) == 80)) { return .many }
			return .other
		}
	)
	
	static let _kab: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0 || i == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _kaj: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _kcg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _kde: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _kea: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _kk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 6) || (absN.truncatingRemainder(dividingBy: 10) == 9) || ((absN.truncatingRemainder(dividingBy: 10) == 0) && (absN != 0)) { return .many }
			return .other
		}
	)
	
	static let _kkj: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _kl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _km: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _kn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ko: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ks: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ksb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ksh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 0 { return .zero }
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ku: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _kw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 0 { return .zero }
			if absN == 1 { return .one }
			if ((absN.truncatingRemainder(dividingBy: 100) == 2 || absN.truncatingRemainder(dividingBy: 100) == 22 || absN.truncatingRemainder(dividingBy: 100) == 42 || absN.truncatingRemainder(dividingBy: 100) == 62 || absN.truncatingRemainder(dividingBy: 100) == 82)) || ((absN.truncatingRemainder(dividingBy: 1000) == 0) && (((1000.0 ... 20000.0).contains(absN.truncatingRemainder(dividingBy: 100000)) || absN.truncatingRemainder(dividingBy: 100000) == 40000 || absN.truncatingRemainder(dividingBy: 100000) == 60000 || absN.truncatingRemainder(dividingBy: 100000) == 80000))) || ((absN != 0) && (absN.truncatingRemainder(dividingBy: 1000000) == 100000)) { return .two }
			if (absN.truncatingRemainder(dividingBy: 100) == 3 || absN.truncatingRemainder(dividingBy: 100) == 23 || absN.truncatingRemainder(dividingBy: 100) == 43 || absN.truncatingRemainder(dividingBy: 100) == 63 || absN.truncatingRemainder(dividingBy: 100) == 83) { return .few }
			if (absN != 1) && ((absN.truncatingRemainder(dividingBy: 100) == 1 || absN.truncatingRemainder(dividingBy: 100) == 21 || absN.truncatingRemainder(dividingBy: 100) == 41 || absN.truncatingRemainder(dividingBy: 100) == 61 || absN.truncatingRemainder(dividingBy: 100) == 81)) { return .many }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if ((1.0 ... 4.0).contains(absN)) || (((1.0 ... 4.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (21.0 ... 24.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (41.0 ... 44.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (61.0 ... 64.0).contains(absN.truncatingRemainder(dividingBy: 100)) || (81.0 ... 84.0).contains(absN.truncatingRemainder(dividingBy: 100)))) { return .one }
			if (absN == 5) || (absN.truncatingRemainder(dividingBy: 100) == 5) { return .many }
			return .other
		}
	)
	
	static let _ky: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lag: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if absN == 0 { return .zero }
			if ((i == 0 || i == 1)) && (absN != 0) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lkt: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ln: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _lt: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (!(11.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .one }
			if ((2.0 ... 9.0).contains(absN.truncatingRemainder(dividingBy: 10))) && (!(11.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _lv: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 0) || ((11.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .zero }
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (absN.truncatingRemainder(dividingBy: 100) != 11) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mas: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mgo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if ((i % 10) == 2) && ((i % 100) != 12) { return .two }
			if (((i % 10) == 7 || (i % 10) == 8)) && (!((i % 100) == 17 || (i % 100) == 18)) { return .many }
			return .other
		}
	)
	
	static let _ml: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _mo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if (!isInteger) || (absN == 0) || ((2.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .few }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _mr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			return .other
		}
	)
	
	static let _ms: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _mt: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if (absN == 0) || ((2.0 ... 10.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .few }
			if (11.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100)) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _my: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _nah: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _naq: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nb: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nd: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ne: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (1.0 ... 4.0).contains(absN) { return .one }
			return .other
		}
	)
	
	static let _nl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nnh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _no: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nqo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _nr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nso: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ny: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _nyn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _om: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _or: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 1 || absN == 5 || (7.0 ... 9.0).contains(absN)) { return .one }
			if (absN == 2 || absN == 3) { return .two }
			if absN == 4 { return .few }
			if absN == 6 { return .many }
			return .other
		}
	)
	
	static let _os: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _osa: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _pa: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _pap: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _pcm: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _pl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			if ((isInteger) && (i != 1) && ((0 ... 1).contains((i % 10)))) || ((isInteger) && ((5 ... 9).contains((i % 10)))) || ((isInteger) && ((12 ... 14).contains((i % 100)))) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _prg: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 0) || ((11.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .zero }
			if (absN.truncatingRemainder(dividingBy: 10) == 1) && (absN.truncatingRemainder(dividingBy: 100) != 11) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ps: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _pt: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (0 ... 1).contains(i) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _pt_PT: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _rm: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ro: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if (!isInteger) || (absN == 0) || ((2.0 ... 19.0).contains(absN.truncatingRemainder(dividingBy: 100))) { return .few }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _rof: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _root: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ru: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			if ((isInteger) && ((i % 10) == 0)) || ((isInteger) && ((5 ... 9).contains((i % 10)))) || ((isInteger) && ((11 ... 14).contains((i % 100)))) { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _rwk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sah: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _saq: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sat: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sc: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 11 || absN == 8 || absN == 80 || absN == 800) { return .many }
			return .other
		}
	)
	
	static let _scn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN == 11 || absN == 8 || absN == 80 || absN == 800) { return .many }
			return .other
		}
	)
	
	static let _sd: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sdh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _se: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _seh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ses: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _sg: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _sh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _shi: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			if (2.0 ... 10.0).contains(absN) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _si: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (absN == 0 || absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			if ((2 ... 4).contains(i)) && (isInteger) { return .few }
			if !isInteger { return .many }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 100) == 1) { return .one }
			if (isInteger) && ((i % 100) == 2) { return .two }
			if ((isInteger) && ((3 ... 4).contains((i % 100)))) || (!isInteger) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sma: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _smi: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _smj: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _smn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sms: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if absN == 2 { return .two }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _so: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _sq: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			if (absN.truncatingRemainder(dividingBy: 10) == 4) && (absN.truncatingRemainder(dividingBy: 100) != 14) { return .many }
			return .other
		}
	)
	
	static let _sr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ss: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ssy: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _st: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _su: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _sv: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if ((absN.truncatingRemainder(dividingBy: 10) == 1 || absN.truncatingRemainder(dividingBy: 10) == 2)) && (!(absN.truncatingRemainder(dividingBy: 100) == 11 || absN.truncatingRemainder(dividingBy: 100) == 12)) { return .one }
			return .other
		}
	)
	
	static let _sw: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _syr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ta: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _te: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _teo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _th: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _ti: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _tig: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _tk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if ((absN.truncatingRemainder(dividingBy: 10) == 6 || absN.truncatingRemainder(dividingBy: 10) == 9)) || (absN == 10) { return .few }
			return .other
		}
	)
	
	static let _tl: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if ((isInteger) && ((i == 1 || i == 2 || i == 3))) || ((isInteger) && (!((i % 10) == 4 || (i % 10) == 6 || (i % 10) == 9))) || (!isInteger) { return .one }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _tn: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _to: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _tr: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ts: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _tzm: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if ((0.0 ... 1.0).contains(absN)) || ((11.0 ... 99.0).contains(absN)) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ug: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _uk: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (isInteger) && ((i % 10) == 1) && ((i % 100) != 11) { return .one }
			if (isInteger) && ((2 ... 4).contains((i % 10))) && (!(12 ... 14).contains((i % 100))) { return .few }
			if ((isInteger) && ((i % 10) == 0)) || ((isInteger) && ((5 ... 9).contains((i % 10)))) || ((isInteger) && ((11 ... 14).contains((i % 100)))) { return .many }
			return .other
		},
		ordinal:  { n in
			let absN = abs(n)
			if (absN.truncatingRemainder(dividingBy: 10) == 3) && (absN.truncatingRemainder(dividingBy: 100) != 13) { return .few }
			return .other
		}
	)
	
	static let _ur: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _uz: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _ve: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _vi: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		}
	)
	
	static let _vo: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _vun: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _wa: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if (0.0 ... 1.0).contains(absN) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _wae: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _wo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _xh: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _xog: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			if absN == 1 { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _yi: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			let isInteger = absN == Double(i)
			if (i == 1) && (isInteger) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
	
	static let _yo: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _yue: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _zh: Self = .init(
		cardinal: { _ in .other },
		ordinal:  { _ in .other }
	)
	
	static let _zu: Self = .init(
		cardinal: { n in
			let absN = abs(n)
			let i = Int(absN.rounded(.down))
			if (i == 0) || (absN == 1) { return .one }
			return .other
		},
		ordinal:  { _ in .other }
	)
}

public extension PluralRule {
	/// CLDR plural rule mapping by BCP-47 language tag.
	/// Keys cover both primary subtags (e.g. "en") and region variants (e.g. "pt-PT")
	/// when CLDR distinguishes them; `Bundle` looks up by primary subtag via `default(for:)`.
	static let defaults: [String: Self] = [
		"af": _af,
		"ak": _ak,
		"am": _am,
		"an": _an,
		"ar": _ar,
		"ars": _ars,
		"as": _as,
		"asa": _asa,
		"ast": _ast,
		"az": _az,
		"be": _be,
		"bem": _bem,
		"bez": _bez,
		"bg": _bg,
		"bho": _bho,
		"bm": _bm,
		"bn": _bn,
		"bo": _bo,
		"br": _br,
		"brx": _brx,
		"bs": _bs,
		"ca": _ca,
		"ce": _ce,
		"ceb": _ceb,
		"cgg": _cgg,
		"chr": _chr,
		"ckb": _ckb,
		"cs": _cs,
		"cy": _cy,
		"da": _da,
		"de": _de,
		"dsb": _dsb,
		"dv": _dv,
		"dz": _dz,
		"ee": _ee,
		"el": _el,
		"en": _en,
		"eo": _eo,
		"es": _es,
		"et": _et,
		"eu": _eu,
		"fa": _fa,
		"ff": _ff,
		"fi": _fi,
		"fil": _fil,
		"fo": _fo,
		"fr": _fr,
		"fur": _fur,
		"fy": _fy,
		"ga": _ga,
		"gd": _gd,
		"gl": _gl,
		"gsw": _gsw,
		"gu": _gu,
		"guw": _guw,
		"gv": _gv,
		"ha": _ha,
		"haw": _haw,
		"he": _he,
		"hi": _hi,
		"hr": _hr,
		"hsb": _hsb,
		"hu": _hu,
		"hy": _hy,
		"ia": _ia,
		"id": _id,
		"ig": _ig,
		"ii": _ii,
		"in": _in,
		"io": _io,
		"is": _is,
		"it": _it,
		"iu": _iu,
		"iw": _iw,
		"ja": _ja,
		"jbo": _jbo,
		"jgo": _jgo,
		"ji": _ji,
		"jmc": _jmc,
		"jv": _jv,
		"jw": _jw,
		"ka": _ka,
		"kab": _kab,
		"kaj": _kaj,
		"kcg": _kcg,
		"kde": _kde,
		"kea": _kea,
		"kk": _kk,
		"kkj": _kkj,
		"kl": _kl,
		"km": _km,
		"kn": _kn,
		"ko": _ko,
		"ks": _ks,
		"ksb": _ksb,
		"ksh": _ksh,
		"ku": _ku,
		"kw": _kw,
		"ky": _ky,
		"lag": _lag,
		"lb": _lb,
		"lg": _lg,
		"lkt": _lkt,
		"ln": _ln,
		"lo": _lo,
		"lt": _lt,
		"lv": _lv,
		"mas": _mas,
		"mg": _mg,
		"mgo": _mgo,
		"mk": _mk,
		"ml": _ml,
		"mn": _mn,
		"mo": _mo,
		"mr": _mr,
		"ms": _ms,
		"mt": _mt,
		"my": _my,
		"nah": _nah,
		"naq": _naq,
		"nb": _nb,
		"nd": _nd,
		"ne": _ne,
		"nl": _nl,
		"nn": _nn,
		"nnh": _nnh,
		"no": _no,
		"nqo": _nqo,
		"nr": _nr,
		"nso": _nso,
		"ny": _ny,
		"nyn": _nyn,
		"om": _om,
		"or": _or,
		"os": _os,
		"osa": _osa,
		"pa": _pa,
		"pap": _pap,
		"pcm": _pcm,
		"pl": _pl,
		"prg": _prg,
		"ps": _ps,
		"pt": _pt,
		"pt-PT": _pt_PT,
		"rm": _rm,
		"ro": _ro,
		"rof": _rof,
		"root": _root,
		"ru": _ru,
		"rwk": _rwk,
		"sah": _sah,
		"saq": _saq,
		"sat": _sat,
		"sc": _sc,
		"scn": _scn,
		"sd": _sd,
		"sdh": _sdh,
		"se": _se,
		"seh": _seh,
		"ses": _ses,
		"sg": _sg,
		"sh": _sh,
		"shi": _shi,
		"si": _si,
		"sk": _sk,
		"sl": _sl,
		"sma": _sma,
		"smi": _smi,
		"smj": _smj,
		"smn": _smn,
		"sms": _sms,
		"sn": _sn,
		"so": _so,
		"sq": _sq,
		"sr": _sr,
		"ss": _ss,
		"ssy": _ssy,
		"st": _st,
		"su": _su,
		"sv": _sv,
		"sw": _sw,
		"syr": _syr,
		"ta": _ta,
		"te": _te,
		"teo": _teo,
		"th": _th,
		"ti": _ti,
		"tig": _tig,
		"tk": _tk,
		"tl": _tl,
		"tn": _tn,
		"to": _to,
		"tr": _tr,
		"ts": _ts,
		"tzm": _tzm,
		"ug": _ug,
		"uk": _uk,
		"ur": _ur,
		"uz": _uz,
		"ve": _ve,
		"vi": _vi,
		"vo": _vo,
		"vun": _vun,
		"wa": _wa,
		"wae": _wae,
		"wo": _wo,
		"xh": _xh,
		"xog": _xog,
		"yi": _yi,
		"yo": _yo,
		"yue": _yue,
		"zh": _zh,
		"zu": _zu,
	]
}
