// @ai-generated(guided)
//
// Generate Sources/SwiftLocalize/GrammaticalGender+Generated.swift from CLDR JSON.
//
// Usage:
//   swift run GenerateGrammaticalGender [<grammaticalFeatures.json|URL>] [<output.swift>]
//
// Source data: https://github.com/unicode-org/cldr-json
//   cldr-core/supplemental/grammaticalFeatures.json
//
// With no source path, fetches `grammaticalFeatures.json` live from the CLDR
// JSON repo (branch defaults to `main`; override via `CLDR_BRANCH`). Pass a
// local file path or HTTP URL to pin a specific snapshot.
//
// The CLDR file is keyed by primary language only (`ru-targets-nominal`,
// `de-targets-nominal`, …) — no region/script variants — so the generated
// table uses the primary subtag as its key and lookup at runtime is a single
// dictionary hit on `language.language`.

import Foundation

// MARK: - CLDR source

let cldrBranch = ProcessInfo.processInfo.environment["CLDR_BRANCH"] ?? "main"
let cldrBase = "https://raw.githubusercontent.com/unicode-org/cldr-json/\(cldrBranch)/cldr-json"

// MARK: - Args

let argv = CommandLine.arguments
let positional = Array(argv.dropFirst()).filter { !$0.hasPrefix("-") }

let inputArg: String? = positional.count >= 1 ? positional[0] : nil
let outputPath: String = positional.count >= 2
	? positional[1]
	: "Sources/SwiftLocalize/GrammaticalGender+Generated.swift"

// MARK: - JSON helpers

func loadJSON(from data: Data, hint: String) throws -> [String: Any] {
	guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
		throw NSError(domain: "GenerateGrammaticalGender", code: 1, userInfo: [
			NSLocalizedDescriptionKey: "Not a JSON object: \(hint)",
		])
	}
	return obj
}

func dict(_ any: Any?) -> [String: Any] { (any as? [String: Any]) ?? [:] }

// MARK: - Load

func loadData(from arg: String?) -> Data {
	if let arg {
		if let url = URL(string: arg), url.scheme == "http" || url.scheme == "https" {
			FileHandle.standardError.write(Data("fetching \(url.absoluteString)\n".utf8))
			do { return try Data(contentsOf: url) } catch {
				FileHandle.standardError.write(Data("failed to fetch \(url): \(error.localizedDescription)\n".utf8))
				exit(1)
			}
		}
		do {
			return try Data(contentsOf: URL(fileURLWithPath: arg))
		} catch {
			FileHandle.standardError.write(Data("failed to read \(arg): \(error.localizedDescription)\n".utf8))
			exit(1)
		}
	}
	let url = URL(string: "\(cldrBase)/cldr-core/supplemental/grammaticalFeatures.json")!
	FileHandle.standardError.write(Data("fetching \(url.absoluteString)\n".utf8))
	do { return try Data(contentsOf: url) } catch {
		FileHandle.standardError.write(Data("failed to fetch grammaticalFeatures.json: \(error.localizedDescription)\n".utf8))
		exit(1)
	}
}

let data = loadData(from: inputArg)

let root: [String: Any]
do {
	root = try loadJSON(from: data, hint: "grammaticalFeatures.json")
} catch {
	FileHandle.standardError.write(Data("parse failed: \(error.localizedDescription)\n".utf8))
	exit(1)
}

// MARK: - Collect
//
// CLDR shape:
//   supplemental.grammaticalData.<locale>-targets-<nominal|...>.grammaticalGender = ["masculine", ...]
//
// We only care about `nominal` targets — the noun/adjective inflection axis,
// which is what the `GrammaticalGender` API is for. Verb targets (where they
// exist) are out of scope.

let supplemental = dict(root["supplemental"])
let grammaticalData = dict(supplemental["grammaticalData"])

/// Mirror of `GrammaticalGender` raw values. Used to flag unknown values from
/// a future CLDR update so the generator fails loud instead of silently
/// emitting a `.fooBar` that won't compile.
let known: Set<String> = ["masculine", "feminine", "neuter", "common", "animate", "inanimate", "personal"]

var rows: [(language: String, genders: [String])] = []

for (key, value) in grammaticalData {
	guard key.hasSuffix("-targets-nominal") else { continue }
	let locale = String(key.dropLast("-targets-nominal".count))
	let entry = dict(value)
	guard let genders = entry["grammaticalGender"] as? [String], !genders.isEmpty else { continue }
	let unknown = Set(genders).subtracting(known)
	if !unknown.isEmpty {
		FileHandle.standardError.write(Data(
			"error: \(locale) has unknown gender value(s) \(unknown.sorted()); update GrammaticalGender enum first\n".utf8
		))
		exit(1)
	}
	rows.append((locale, genders))
}

rows.sort { $0.language < $1.language }

// MARK: - Emit

var output = ""
output += "// @ai-generated(guided) — DO NOT EDIT BY HAND.\n"
output += "// Generated by Scripts/GenerateGrammaticalGender from CLDR data.\n"
output += "// Regenerate after CLDR updates:\n"
output += "//   swift run GenerateGrammaticalGender [<grammaticalFeatures.json|URL>] [<output.swift>]\n"
output += "//\n"
output += "// Source: https://github.com/unicode-org/cldr-json (cldr-core/supplemental/grammaticalFeatures.json)\n"
output += "import Foundation\n\n"

output += "internal enum GrammaticalGenderData {\n\n"
output += "\t/// Grammatical genders per language per CLDR `grammaticalFeatures.json`.\n"
output += "\t/// Keyed by primary BCP-47 subtag (`ru`, `de`, `cs`). Languages absent\n"
output += "\t/// from this map have no grammatical gender system (en, ja, zh, …).\n"
output += "\tstatic let genders: [String: Set<GrammaticalGender>] = [\n"
for (lang, gs) in rows {
	let items = gs.map { ".\($0)" }.joined(separator: ", ")
	output += "\t\t\"\(lang)\": [\(items)],\n"
}
output += "\t]\n"
output += "}\n"

try output.write(to: URL(fileURLWithPath: outputPath), atomically: true, encoding: .utf8)
print("wrote \(outputPath): languages=\(rows.count)")
